name: Rust

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  test_without_otel:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1.8.0
      - name: "Test"
        run: cargo test

  test_with_otel:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otel_version:
          - opentelemetry_0_13
          - opentelemetry_0_14
          - opentelemetry_0_15
          - opentelemetry_0_16
          - opentelemetry_0_17
          - opentelemetry_0_18
          - opentelemetry_0_19
          - opentelemetry_0_20
          - opentelemetry_0_21
          - opentelemetry_0_22
          - opentelemetry_0_23
          - opentelemetry_0_24
          - opentelemetry_0_25
          - opentelemetry_0_26
          - opentelemetry_0_27
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1.8.0
      - name: "Test"
        run: cargo test --features ${{ matrix.otel_version }}

  test_uuid_v7:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1.8.0
      - name: "Test"
        run: cargo test --features uuid_v7

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1.8.0
        with:
          components: rustfmt
      - name: "Rustfmt Check"
        run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1.8.0
        with:
          components: clippy
      - name: "Clippy Check"
        run: cargo clippy -- -D warnings
